Imports System.IO

''' <summary>
''' The options of the <see cref="ApiDoc"/> api reference document generator.
''' </summary>
Public Class ApiDocOptions

    ''' <summary>
    ''' The input that provides the .net xml comment documents. It could be:
    ''' 
    ''' + a single ``*.xml`` comment document file;
    ''' + a single clr assembly file (``*.dll`` / ``*.exe``), then its sibling
    '''   ``*.xml`` comment document will be loaded;
    ''' + a directory that contains one or more ``*.xml`` comment documents,
    '''   all of them will be merged into one document site.
    ''' </summary>
    ''' <returns></returns>
    Public Property Input As String

    ''' <summary>
    ''' The output directory of the generated static html document site.
    ''' This option is required and it has no default value.
    ''' </summary>
    ''' <returns></returns>
    Public Property Output As String

    ''' <summary>
    ''' The name of a built-in theme, or a directory that contains an external
    ''' theme. The default value is the ``scibasic`` dark theme which is aligned
    ''' with the web front end of the nuget package server.
    ''' </summary>
    ''' <returns></returns>
    Public Property Theme As String = ThemeAssets.DefaultTheme

    ''' <summary>
    ''' The site title that is displayed in the page header and in the html title.
    ''' </summary>
    ''' <returns></returns>
    Public Property Title As String = "API Reference"

    ''' <summary>
    ''' The sub title that is displayed next to the site title.
    ''' </summary>
    ''' <returns></returns>
    Public Property SubTitle As String = "code api reference"

    ''' <summary>
    ''' A one sentence description that is displayed on the index page.
    ''' </summary>
    ''' <returns></returns>
    Public Property Description As String = "A static api reference document site which is generated from the .net xml comment documents."

    ''' <summary>
    ''' Excludes the ``My.Resources`` members which are generated by the vb
    ''' compiler automatically.
    ''' </summary>
    ''' <returns></returns>
    Public Property ExcludeVBSpecific As Boolean = True

    ''' <summary>
    ''' Clean the output directory before the site generation.
    ''' </summary>
    ''' <returns></returns>
    Public Property Clean As Boolean = True

    ''' <summary>
    ''' Reflects the sibling clr assembly of every xml comment document to
    ''' supplement the members which carry no xml comment (for example the
    ''' undocumented members of an enum). only the public members are
    ''' supplemented, and a reflection failure is only a warning.
    ''' </summary>
    ''' <returns></returns>
    Public Property ReflectSupplement As Boolean = True

    ''' <summary>
    ''' Check the input option, returns an error message when the input is
    ''' invalid, or nothing when everything is fine. The output directory is not
    ''' required by the data extract stage.
    ''' </summary>
    ''' <returns></returns>
    Friend Function ValidateInput() As String
        If String.IsNullOrWhiteSpace(Input) Then
            Return "the input path is required."
        End If

        If Not File.Exists(Input) AndAlso Not Directory.Exists(Input) Then
            Return $"the input path does not exist: {Input}"
        End If

        Return Nothing
    End Function

    ''' <summary>
    ''' Check the options, returns an error message when the options are invalid,
    ''' or nothing when everything is fine.
    ''' </summary>
    ''' <returns></returns>
    Friend Function Validate() As String
        Dim errorMessage As String = ValidateInput()

        If Not String.IsNullOrEmpty(errorMessage) Then
            Return errorMessage
        End If

        If String.IsNullOrWhiteSpace(Output) Then
            Return "the output directory is required."
        End If

        Return Nothing
    End Function
End Class
