<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Readership</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Themes\scibasic.css" LogicalName="Readership.Themes.scibasic.css" />
    <EmbeddedResource Include="Themes\docs.css" LogicalName="Readership.Themes.docs.css" />
    <EmbeddedResource Include="Themes\docs.js" LogicalName="Readership.Themes.docs.js" />
    <EmbeddedResource Include="Themes\favicon.png" LogicalName="Readership.Themes.favicon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\Data_science\Graph\graph-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\Data_science\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\mime\application%json\JSON-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\mime\text%markdown\markdown.NET5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\nlp\NLP\NLP.NET.vbproj" />
  </ItemGroup>

</Project>
