<Project Sdk="Microsoft.VisualBasic.NET.Sdk/10.0.100">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>seed</RootNamespace>
    <AssemblyName>seed</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <StartupObject>seed.Seed</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Nuget\Nuget.vbproj" />
    <ProjectReference Include="..\..\Readership\Readership.vbproj" />
  </ItemGroup>
</Project>
